name: Checkmarx One Scan

# Required permissions for the GitHub token
permissions:
  contents: read
  pull-requests: write
  security-events: write

on:
  pull_request:
    branches:
      - "**"  # Scans for all branches on PRs

jobs:
  cxone_scan:
    name: Checkmarx One Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Run Checkmarx One Scan
        uses: checkmarx/ast-github-action@v2.0.23
        with:
          base_uri: ${{ secrets.CX_BASE_URI }}
          cx_tenant: ${{ secrets.CX_TENANT }}
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          project_name: ${{ github.repository }}
          branch: ${{ github.ref_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_dir: .
          additional_params: --report-format sarif --output-path .

      - name: Upload SARIF file to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: cx_result.sarif
