name: Checkmarx One SAST Scan

permissions:
  contents: read
  security-events: write
  pull-requests: write

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Checkmarx One Scan
        uses: checkmarx/ast-github-action@main
        with:
          base_uri: ${{ secrets.CX_BASE_URI }}
          cx_tenant: ${{ secrets.CX_TENANT }}
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          project_name: ${{ github.repository }}
          branch: ${{ github.ref_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
