name: Checkmarx Scan

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  cxone:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Checkmarx One Scan
      uses: Checkmarx/ast-github-action@2.0.23
      with:
        base_uri: ${{ secrets.CX_BASE_URI }}
        cx_tenant: ${{ secrets.CX_TENANT }}
        cx_client_id: ${{ secrets.CX_CLIENT_ID }}
        cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
        project_name: "my-cxone-project"
        branch: ${{ github.ref_name }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
