name: Checkmarx One Scan
on:
  push:
    branches:
      - main
      - master
      - dev
permissions:
  contents: read
  security-events: write
  actions: read
  pull-requests: write
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - name: Run Checkmarx One CLI
        uses: checkmarx/ast-github-action@main
        with:
          project_name: CxGitHubActionJamna
          cx_tenant: DP_WP_Account
          base_uri: https://eu.ast.checkmarx.net/
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params: --report-format sarif --output-path cx_result.sarif
          
